### ISSUE TITLE
Grid system is not very adaptable

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe-themes/silverstripe-simple#16]
I suggest pulling out some of the grid-system styles and putting them together so the grid can be adapted easier for individual projects. The use of something like http://gridpak.com/ would allow for users to easily adapt this theme for device sizes easily. This should be done in a very minimalistic way so that it is easily understood by beginners.

**Comment by dnsl48** [comment]
Closing this for now. Can reopen later if necessary. 
https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests
