### ISSUE TITLE
A UI issue - Search From

### ISSUE THREAD

**Issue by nadeeth** [silverstripe-themes/silverstripe-simple#25]
Search form overlaps with the main menu in the default (simple) theme.
 Please see the attached screen shot.

 To fix, please remove the line 174 of "themes/simple/css/layout.css" (top:
 32px;).
![ss_search_form](https://f.cloud.github.com/assets/3961699/296903/ecae608c-951c-11e2-91ec-ffa06a0b8968.png)

**Comment by robbieaverill** [comment]
Can't reproduce now with SilverStripe 4.3
