### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by stevie-mayhew** [silverstripe-themes/silverstripe-simple#35]
Would it be possible to get a non-rc tag for this? Would be good to be able to remove `minimum-stability: dev` in composer files when relying on this theme.

Originally pointed out by @simonwelsh in IRC
```
[11:43:59]  <@simon_w|air>	 You know what's not tagged, so breaks when fixing the minimum stability?
[11:44:02]  <@simon_w|air>	 The simple theme
```

**Comment by tractorcow** [comment]
done. :) 3.1.0 added

**Comment by stevie-mayhew** [comment]
Thanks @tractorcow
