### ISSUE TITLE
Tag 3.2.0

### ISSUE THREAD

**Issue by andrewandante** [silverstripe-themes/silverstripe-simple#56]
With the `expose`s being added in, a new tag should be made for `3.2.0` to go with SS4 installs, so that a user doesn't have to resort to `dev-master` or `3.2.x-dev` to get a working version in. This is particularly important as a `composer require` will bring in `^3.1` - bringing in `3.1.1` - by default, especially when using something like `recipe-cms`

**Comment by dhensby** [comment]
done
